server:
  port: 8848
spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: abc12345
    url: jdbc:mysql://127.0.0.1:3306/aitag
    type: com.alibaba.druid.pool.DruidDataSource
mybatis-plus:
  #信息输出设置
  # xml地址
  mapper-locations:  classpath:mapper/*.xml
  # 实体扫描，多个package用逗号或者分号分隔
  # type-aliases-package: ***   #自己的实体类地址
#上传时出现如下异常:  上传文件的大小超出默认配置  	默认10M